# Book settings
title: Climate and Geophysical Data Analysis
author: Karen Smith
description: >-
  Interactive courseware on climate and geophysical data analysis
copyright: "2020"  # Copyright year to be placed in the footer
logo: gistemp.png
################################################################################
# Execution settings
execute:
  execute_notebooks         : auto  # Whether to execute notebooks at build time. Must be one of ("auto", "force", "cache", "off")
  cache                     : ""  # A path to the jupyter cache that will be used to store execution artifacs. Defaults to `_build/.jupyter_cache/`
  exclude_patterns          : []  # A list of patterns to *skip* in execution (e.g. a notebook that takes a really long time)

################################################################################
# HTML-specific settings
html:
  favicon                   : ""  # A path to a favicon image
  use_edit_page_button      : false  # Whether to add an "edit this page" button to pages. If `true`, repository information in repository: must be filled in
  use_repository_button     : false  # Whether to add a link to your repository button
  use_issues_button         : false  # Whether to add an "open an issue" button
  extra_navbar              : Powered by <a href="https://jupyterbook.org">Jupyter Book</a>  # Will be displayed underneath the left navbar.
  extra_footer              : ""  # Will be displayed underneath the footer.
  google_analytics_id       : ""  # A GA id that can be used to track book views.
  home_page_in_navbar       : true  # Whether to include your home page in the left Navigation Bar
  baseurl                   : https://kls2177.github.io/Climate-and-Geophysical-Data-Analysis/chapters/index.html  # The base URL where your book will be hosted. Used for creating image previews and social links. e.g.: https://mypage.com/mybook/

################################################################################
# Launch button settings
launch_buttons:
  notebook_interface        : classic  # The interface interactive links will activate ["classic", "jupyterlab"]
  binderhub_url             : https://mybinder.org  # The URL of the BinderHub (e.g., https://mybinder.org)
  jupyterhub_url            : ""  # The URL of the JupyterHub (e.g., https://datahub.berkeley.edu)
  thebe                     : true  # Add a thebe button to pages (requires the repository to run on Binder)

repository:
  url                       : https://github.com/kls2177/Climate-and-Geophysical-Data-Analysis  # Online location of your book
  path_to_book              : ""  # Optional path to your book, relative to the repository root
  branch                    : master  # Which branch of the repository should be used when creating links (optional)

################################################################################
# Advanced and power-user settings
sphinx:
  extra_extensions          :   # A list of extra extensions to load by Sphinx.
  config                    :   # key-value pairs to directly over-ride the Sphinx configuration

###############################################################################
latex:
  latex_documents:
    targetname: book.tex
